//ANALOG INPUT PINS
#define ADAPTER_VOLTAGE_PIN 0
#define BATTERY_VOLTAGE_PIN 1

#define UPS_CURRENT_OUT_PIN 7
#define BATTERY_CURRENT_IN_PIN 3

//DIGITAL OUTPUT PINS
#define BAT_FET_PIN 0
#define CHARGE_FET_PIN 1

//POWER BUTTON PINS
#define POWER_BUT_SENSE_PIN A6
#define POWER_BUT_SEND_PIN A2
